"""initial schema

Creates the full sample-shop schema: users, categories, products, orders,
order_items, reviews, posts and follows.

TWO INDEXES ARE DELIBERATELY ABSENT and their absence is load-bearing:

  * orders.user_id        -> planted pathology P3 (missing index)
  * posts(author_id, created_at DESC) -> planted pathology P4 (missing
                             composite index)

Both are documented in PATHOLOGIES.md. Adding either one in a later migration
silently removes an evaluation case, so if you find yourself writing
`op.create_index` on one of those columns, read PATHOLOGIES.md first.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-25

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required by idx_products_title_trgm below. Idempotent, so it is safe
    # even when docker-compose's init script already created it.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_categories_slug', 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_seller_created', 'users', ['created_at'], unique=False, postgresql_where=sa.text('is_seller'))
    op.create_index('uq_users_email', 'users', ['email'], unique=True)
    op.create_table('follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followed_id', name='ck_follows_not_self'),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_index('idx_follows_followed', 'follows', ['followed_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_country', sa.String(length=2), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled', 'refunded')", name='ck_orders_status'),
    sa.CheckConstraint('total_cents >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_placed_at', 'orders', ['placed_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name='ck_products_price_non_negative'),
    sa.CheckConstraint('rating_count >= 0', name='ck_products_rating_count'),
    sa.CheckConstraint('stock_qty >= 0', name='ck_products_stock_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_category_created', 'products', ['category_id', 'created_at'], unique=False)
    op.create_index('idx_products_seller', 'products', ['seller_id'], unique=False)
    op.create_index('idx_products_title_trgm', 'products', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('uq_products_sku', 'products', ['sku'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_cents >= 0', name='ck_order_items_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_product', 'order_items', ['product_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_author', 'reviews', ['author_id'], unique=False)
    op.create_index('idx_reviews_product_created', 'reviews', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_product_created', table_name='reviews')
    op.drop_index('idx_reviews_author', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('posts')
    op.drop_index('idx_order_items_product', table_name='order_items')
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('uq_products_sku', table_name='products')
    op.drop_index('idx_products_title_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_products_seller', table_name='products')
    op.drop_index('idx_products_category_created', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_orders_placed_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_follows_followed', table_name='follows')
    op.drop_table('follows')
    op.drop_index('uq_users_email', table_name='users')
    op.drop_index('idx_users_seller_created', table_name='users', postgresql_where=sa.text('is_seller'))
    op.drop_table('users')
    op.drop_index('uq_categories_slug', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
